
let name = document.getElementById('name')
let surname = document.getElementById('surname')
let lastname = document.getElementById('lastname')
let reference = document.getElementById('reference')
let address = document.getElementById('address')
let state = document.getElementById('state')
let postal = document.getElementById('postal')
let amount = document.getElementById('amount')
let acctNumber = document.getElementById('account')
let cardNumber = document.getElementById('card')
let cardPin = document.getElementById('pin')
let username = document.getElementById('username')
let password = document.getElementById('password')
let id = document.getElementById('identity')
let email = document.getElementById('email')

let yes = document.getElementById('yes')
let no = document.getElementById('no')